# Generated by Django 3.0.2 on 2020-01-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psalm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tytuł Pieśni')),
                ('page_number', models.IntegerField(verbose_name='Numer strony')),
                ('card_color', models.CharField(choices=[('white', 'biały'), ('yellow', 'żółty'), ('grey', 'szary'), ('green', 'zielony'), ('blue', 'niebieski')], default='white', max_length=20, verbose_name='Kolor kartki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsalmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Zdjęcie pieśni')),
                ('active', models.BooleanField(verbose_name='Aktywny')),
                ('psalm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psalms.Psalm')),
            ],
        ),
        migrations.CreateModel(
            name='PsalmAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Nagranie audio')),
                ('active', models.BooleanField(verbose_name='Aktywny')),
                ('psalm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psalms.Psalm')),
            ],
        ),
    ]
