# Generated by Django 3.0.2 on 2020-01-29 14:14

from django.db import migrations, models
import neo_guide.psalms.utils


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psalmaudio',
            name='audio',
            field=models.FileField(upload_to=neo_guide.psalms.utils.psalm_audio_directory_path, verbose_name='Nagranie audio'),
        ),
        migrations.AlterField(
            model_name='psalmimage',
            name='image',
            field=models.ImageField(upload_to=neo_guide.psalms.utils.psalm_image_directory_path, verbose_name='Zdjęcie pieśni'),
        ),
    ]
