# Generated by Django 3.0.2 on 2020-01-29 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import neo_guide.psalms.utils
import neo_guide.psalms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0002_auto_20200129_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psalm',
            options={'ordering': ['page_number'], 'verbose_name': 'Psalm', 'verbose_name_plural': 'Psalmy'},
        ),
        migrations.AlterModelOptions(
            name='psalmaudio',
            options={'ordering': ['psalm__page_number'], 'verbose_name': 'Nagranie psalmu', 'verbose_name_plural': 'Nagrania psalmów'},
        ),
        migrations.AlterModelOptions(
            name='psalmimage',
            options={'ordering': ['psalm__page_number'], 'verbose_name': 'Zdjęcie psalmu', 'verbose_name_plural': 'Zdjęcia psalmów'},
        ),
        migrations.AddField(
            model_name='psalmaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psalmaudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='psalmimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psalmimage',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Domyślny'),
        ),
        migrations.AddField(
            model_name='psalmimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='psalm',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tytuł Pieśni'),
        ),
        migrations.AlterField(
            model_name='psalm',
            name='page_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Numer strony'),
        ),
        migrations.AlterField(
            model_name='psalmaudio',
            name='audio',
            field=models.FileField(help_text='.mp3, .wav, .wma lub flac', upload_to=neo_guide.psalms.utils.psalm_audio_directory_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'wma', 'flac']), neo_guide.psalms.validators.validate_audio_file_size], verbose_name='Nagranie audio'),
        ),
        migrations.AlterField(
            model_name='psalmaudio',
            name='psalm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psalm_audio', to='psalms.Psalm'),
        ),
        migrations.AlterField(
            model_name='psalmimage',
            name='image',
            field=models.ImageField(upload_to=neo_guide.psalms.utils.psalm_image_directory_path, validators=[neo_guide.psalms.validators.validate_image_file_size], verbose_name='Zdjęcie pieśni'),
        ),
        migrations.AlterField(
            model_name='psalmimage',
            name='psalm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psalm_image', to='psalms.Psalm'),
        ),
    ]
