# Generated by Django 3.0.2 on 2020-01-30 13:42

import django.core.validators
from django.db import migrations, models
import neo_guide.psalms.utils
import neo_guide.psalms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0003_auto_20200129_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='psalm',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='psalmaudio',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='psalmaudio',
            name='audio',
            field=models.FileField(blank=True, help_text='.mp3, .wav, .wma lub flac', upload_to=neo_guide.psalms.utils.psalm_audio_directory_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'wma', 'flac']), neo_guide.psalms.validators.validate_audio_file_size], verbose_name='Nagranie audio'),
        ),
        migrations.AlterField(
            model_name='psalmimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='psalmimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=neo_guide.psalms.utils.psalm_image_directory_path, validators=[neo_guide.psalms.validators.validate_image_file_size], verbose_name='Zdjęcie pieśni'),
        ),
    ]
