# Generated by Django 3.0.2 on 2020-02-07 14:02

import django.core.validators
from django.db import migrations, models
import neo_guide.psalms.utils
import neo_guide.psalms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0004_auto_20200130_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psalmimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=neo_guide.psalms.utils.psalm_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), neo_guide.psalms.validators.validate_image_file_size], verbose_name='Zdjęcie pieśni'),
        ),
    ]
