# Generated by Django 3.0.2 on 2020-02-10 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0005_auto_20200207_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psalm',
            name='page_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Numer strony'),
        ),
    ]
