# Generated by Django 3.0.3 on 2020-05-03 10:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('psalms', '0009_auto_20200426_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psalm',
            name='neo_stage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pre_catechumenate', 'Śpiew Prekatechumenat'), ('first_scrutinium', 'Śpiew etapu "I Scrutinium"'), ('shema', 'Śpiew etapu "Shema"'), ('second_scrutinium', 'Śpiew etapu "II Scrutinium"'), ('introduction_to_prayer', 'Śpiew etapu "Wprowadzenie w modlitwę"'), ('traditio', 'Śpiew etapu "Traditio"'), ('reditio', 'Śpiew etapu "Reditio"'), ('our_father', 'Śpiew etapu "Ojcze nasz"'), ('choosing', 'Śpiew etapu "Wybranie"'), ('baptism', 'Śpiew etapu "Odnowienie przyrzeczeń chrzcielnych"')], max_length=126, null=True, verbose_name='Etap'),
        ),
    ]
