exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
    - id: isort
      additional_dependencies:
        - toml
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [--line-length, '120', --skip-string-normalization]
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, production]
