version: 0.0
os: linux
#files:
#  - source: /
#    destination: /var/www/html
#    overwrite: true
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy-scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy-scripts/validate_service
      timeout: 300
      runas: root
