version: "3.7"

x-env-var: &env_var
  environment:
    SECRET_KEY: "$SECRET_KEY"
    DEBUG: "$DEBUG"
    ADMIN_URL: 'admin/'
    ALLOWED_HOSTS: "$ALLOWED_HOSTS"
    CORS_ORIGIN_WHITELIST: "$CORS_ORIGIN_WHITELIST"
    DATABASE_URL: "$DATABASE_URL"
    AWS_STORAGE_BUCKET_NAME: "$AWS_STORAGE_BUCKET_NAME"
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"


x-base:
  &base
  <<: *env_var
  build: .

services:
  backend:
    <<: *base
    container_name: neo_guide-backend
    restart: always
    ports:
      - "80:3000"
    command: >
      bash -c "python wait_for_postgres.py &&
               python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn -b [::]:3000 config.wsgi"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      API_URL: "http://0.0.0.0:8000/swagger.json"
