version: "3.7"
volumes:
  db_volume:
  redis_volume:

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./.env

x-base:
  &base
  <<: *env_file
  build: .
  volumes:
    - .:/app

services:
  backend:
    <<: *base
    container_name: neo_guide-backend
    ports:
      - 8000:8000
    depends_on:
      - db
    command: >
      bash -c "python wait_for_postgres.py &&
               python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    <<: *env_file
    container_name: neo_guide-db
    image: postgres:11
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      API_URL: "http://0.0.0.0:8000/swagger.json"
  redis:
    container_name: neo_guide-redis
    image: redis:alpine
    volumes:
      - redis_volume:/var/lib/redis
    ports:
      - 6379:6379

  celery_worker:
    <<: *base
    container_name: neo_guide-celery-worker
    command: celery worker -A config.celery -l info

  celery_beat:
    <<: *base
    container_name: neo_guide-celery-beat
    command: celery beat -A config.celery -l info
