# Generated by Django 3.0.3 on 2020-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wspólnota'),
        ),
        migrations.AddField(
            model_name='user',
            name='parish',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parafia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwisko'),
        ),
    ]
